### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by Droyk** [thecog19/Reddit_Visualizer#4]
![image](https://user-images.githubusercontent.com/15848350/55284137-3f103900-538e-11e9-8819-c523cee89915.png)

Possible to fix?

**Comment by thecog19** [comment]
We discontinued running the application on heroku due to cost reasons. If you're interested, you should be able to run the app locally following the instructions on the readme.

**Comment by Droyk** [comment]
So fix won't be possible that's sad. 
anyway, thanx for the fast response.
